### ISSUE TITLE
Add more-itertools functions

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [make-github-pseudonymous-again/js-itertools#105]
See https://github.com/more-itertools/more-itertools

**Comment by aureooms** [comment]
Also take inspiration from more-itertools classification of function. The current one (`base`, `extra`, `map`, `reduce`) is not correct.

**Comment by make-github-pseudonymous-again** [comment]
This has been partially fixed through splitting up things. more-itertools is now clearly referenced. Will reopen or open new dedicated issues if need be. Closing for now.
